const preguntasDeportes = [
    {
        id: 1,
        pregunta: "Cada cuantos años se hacen los Juegos Olimpicos?",
        opciones: [2, 4, 6, 8],
        correcta: "4",
    },
    {
        id: 2,
        pregunta: "Cuantos titulos de Roland Garros tiene Rafael Nadal?",
        opciones: [11, 12, 13, 14],
        correcta: "14",
    },
    {
        id: 3,
        pregunta: "Cuantos balones de oro tiene Lionel Messi?",
        opciones: [5, 6, 7, 8],
        correcta: "7",
    },
    {
        id: 4,
        pregunta: "Cuantos hoyos hay en una ronda de golf promedio?",
        opciones: [18, 20, 15, 12],
        correcta: "18",
    },
    {
        id: 5,
        pregunta: "Cuantos metros tiene de largo una pileta olimpica?",
        opciones: [30, 80, 50, 100],
        correcta: "50",
    },
    {
        id: 6,
        pregunta: "Cuantos puntos vale un try en el rugby?",
        opciones: [2, 5, 7, 10],
        correcta: "5",
    },
    {
        id: 7,
        pregunta: "Cuantos jugadores hay en un equipo de beisbol?",
        opciones: [7, 11, 9, 13],
        correcta: "9",
    },
    {
        id: 8,
        pregunta: "Que tipo de carrera es el tour de Francia?",
        opciones: ["Formula 1", "Maraton", "Turismo Carretera", "Ciclismo"],
        correcta: "Ciclismo",
    },
    {
        id: 9,
        pregunta: "Cual es el equipo mas antiguo del futbol argentino?",
        opciones: ["River", "Racing", "Rosario Central", "Gimnasia de la Plata"],
        correcta: "Gimnasia de la Plata",
    },
    {
        id: 10,
        pregunta: "Cuantos anillos de la NBA gano Michael Jordan?",
        opciones: [4, 5, 6, 7],
        correcta: "6",
    },
    {
        id: 11,
        pregunta: "Que pais jugo todos los mundiales de futbol?",
        opciones: ["Brasil", "Argentina", "Italia", "Alemania"],
        correcta: "Brasil",
    },
    {
        id: 12,
        pregunta: "Cuantos anillos hay en el logo de los Juegos Olimpicos?",
        opciones: [4, 5, 6, 7],
        correcta: "6",
    },
    {
        id: 13,
        pregunta: "En que equipo de la NBA juega Lebron James?",
        opciones: ["Miami Heat", "Cleveland Cavaliers", "Los Angeles Lakers", "Brookling Nets"],
        correcta: "Los Angeles Lakers",
    },
    {
        id: 14,
        pregunta: "Que seleccion gano el primer mundial de futbol?",
        opciones: ["Brasil", "Argentina", "Uruguay", "Italia"],
        correcta: "Uruguay",
    },
    {
        id: 15,
        pregunta: "Quien es el maximo goleador en la historia de los mundiales de futbol?",
        opciones: ["Lionel Messi", "Cristiano Ronaldo", "Miroslav Klose", "Ronaldo Nazario"],
        correcta: "Miroslav Klose",
    },
    {
        id: 16,
        pregunta: "En que club portugues jugo Cristiano Ronaldo?",
        opciones: ["Sporting Lisboa", "Benfica", "Porto", "Braga"],
        correcta: "Sporting Lisboa",
    },
    {
        id: 17,
        pregunta: "Que numero uso Messi en el Barcelona ademas del 30 y del 10?",
        opciones: [16, 19, 7, 9],
        correcta: "19",
    },
    {
        id: 18,
        pregunta: "Quien es el unico jugador en ganar la Champions League con 3 equipos distintos?",
        opciones: ["Cristiano Ronaldo", "Ronaldinho", "Zidane", "Seedorf"],
        correcta: "Seedorf",
    },
    {
        id: 19,
        pregunta: "Cuantas Champions League gano Messi con el Barcelona?",
        opciones: [3, 4, 5, 6],
        correcta: "4",
    },
    {
        id: 20,
        pregunta: "Cuantas Champions League gano el Real Madrid?",
        opciones: [10, 11, 13, 14],
        correcta: "14",
    },
    {
        id: 21,
        pregunta: "En que año se jugo el primer mundial de futbol?",
        opciones: [1922, 1926, 1930, 1936],
        correcta: "1930",
    },
    {
        id: 22,
        pregunta: "Que seleccion gano mas mundiales de futbol?",
        opciones: ["Italia", "Alemania", "Francia", "Brasil"],
        correcta: "Brasil",
    },
    {
        id: 23,
        pregunta: "Cual es el equipo mas ganador de la Premier League?",
        opciones: ["Manchester United", "Liverpool", "Chelsea", "Manchester City"],
        correcta: "Manchester United",
    },
    {
        id: 24,
        pregunta: "En que pais nacio Usain Bolt?",
        opciones: ["Estados Unidos", "Senegal", "Jamaica", "Inglaterra"],
        correcta: "Jamaica",
    },
    {
        id: 25,
        pregunta: "Cuantas medallas de oro gano Usain Bolt en los Juegos Olimpicos?",
        opciones: [6, 8, 10, 12],
        correcta: "8",
    },
    {
        id: 26,
        pregunta: "Cuantas medallas olimpicas tiene Michael Phelps en total?",
        opciones: [20, 28, 30, 33],
        correcta: "28",
    },
    {
        id: 27,
        pregunta: "Cual de estos tenistas gano una medalla de oro en los Juegos Olimpicos?",
        opciones: ["Novak Djokovic", "Roger Federer", "Juan Martin Del Potro", "Rafael Nadal"],
        correcta: "Rafael Nadal",
    },
    {
        id: 28,
        pregunta: "En el tenis: cuantos torneos de Grand Slam hay en un año?",
        opciones: [4, 5, 6, 7],
        correcta: "4",
    },
    {
        id: 29,
        pregunta: "Cuantos titulos de Grand Slam tiene Roger Federer?",
        opciones: [15, 18, 20, 21],
        correcta: "20",
    },
    {
        id: 30,
        pregunta: "Cuantos anillos de la NBA gano Manu Ginobili?",
        opciones: [2, 3, 4, 5],
        correcta: "4",
    },
    {
        id: 31,
        pregunta: "Cual es el jugador con mas anillos de la NBA?",
        opciones: ["Sam Jones", "Lebron James", "Kevin Durant", "Bill Russell"],
        correcta: "Bill Russell",
    },
    {
        id: 32,
        pregunta: "Cuantas copas America gano Diego Armando Maradona?",
        opciones: [0, 1, 2, 3],
        correcta: "0",
    },
    {
        id: 33,
        pregunta: "Cuantos goles hizo Diego Armando Maradona en el mundial de 1986?",
        opciones: [4, 5, 6, 7],
        correcta: "5",
    },
    {
        id: 34,
        pregunta: "Cuantas Copas America gano la seleccion Argentina de futbol?",
        opciones: [12, 13, 14, 15],
        correcta: "15",
    },
    {
        id: 35,
        pregunta: "Donde se juega el US Open de tenis?",
        opciones: ["Nueva York", "Chicago", "Los Angeles", "Las Vegas"],
        correcta: "Nueva York",
    },
    {
        id: 36,
        pregunta: "En que equipo de la NBA juega Facundo Campazzo?",
        opciones: ["Milwaukee Bucks", "Toronto Raptors", "Boston Celtics", "Denver Nuggets"],
        correcta: "Denver Nuggets",
    },
    {
        id: 37,
        pregunta: "En que año se retiro definitivamente Diego Armando Maradona?",
        opciones: [1995, 1996, 1997, 1998],
        correcta: "1997",
    },
    {
        id: 38,
        pregunta: "En que equipo se retiro oficialmente Michael Jordan?",
        opciones: ["Washington Wizards", "Chicago Bulls", "Memphis Grizzlies", "Detroit Pistons"],
        correcta: "Washington Wizards",
    },
    {
        id: 39,
        pregunta: "En cual de estos equipos no jugo Carlos Tevez?",
        opciones: ["Manchester United", "Manchester City", "West Ham United", "Southampton"],
        correcta: "Southampton",
    },
    {
        id: 40,
        pregunta: "En donde serán los Juegos Olímpicos de 2026?",
        opciones: ["Madrid", "Paris", "Tokio", "Rio de Janeiro"],
        correcta: "Paris",
    }
]